FROM ghcr.io/mlflow/mlflow:v3.7.0

# Install PostgreSQL client library and curl for health checks
RUN pip install psycopg2-binary && \
    apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

# Use the same entrypoint as the base image
ENTRYPOINT ["mlflow"]